"""The neural quantile model — phase P3, learning on synthetic data.

P3's exit condition: the training pipeline converges on a synthetic series with
**known** structure and recovers that structure.

"Recovers" is tested against the truth rather than against a leaderboard. The
generating process here is an AR(1) on log steps, so the conditional expectation
of the cumulative log return is available in closed form — `s · (φ + φ² + φ³)`
for a last step `s`. The load-bearing assertion correlates the model's predicted
median against *that*, not against realised prices, because a model can track
realised prices by luck and cannot track the true conditional mean by luck.

Two controls sit either side of it:

* a **random walk**, where the model must fail to beat persistence. A test suite
  that only demonstrates success cannot tell a working evaluation from a
  flattering one.
* **determinism**, because a fit that produces different weights each run cannot
  be compared with anything, including itself.

**What this does not show.** Every series is synthetic and generated by a process
this file wrote. Passing proves the pipeline can learn a structure that is
genuinely there; it says nothing about markets. `docs/OLYMPUS_NATIVE_MODEL_STATUS.md`
is the ledger, and blocker B1 — no reachable market data — is why.
"""

from __future__ import annotations

import math
import random
import statistics
from datetime import datetime, timedelta, timezone

import pytest

from olympus.trading.clock import FixedClock
from olympus.trading.contracts import Candle
from olympus.trading.errors import ConfigurationError, DependencyMissing
from olympus.trading.evaluate import paired_bootstrap
from olympus.trading.native import checkpoint as CP
from olympus.trading.native import data as D
from olympus.trading.native import encoder as E
from olympus.trading.native import forecaster as F
from olympus.trading.native import neural as N
from olympus.trading.native import torchutil as TU
from olympus.trading.native import train as T
from olympus.trading.native import trunk as TR
from olympus.trading.native.quantile import (DECLINE_NOT_FITTED, Declined,
                                             quantile_label)

pytestmark = pytest.mark.skipif(not TU.torch_available(),
                                reason="torch is an optional `native` extra")

START = datetime(2027, 3, 1, tzinfo=timezone.utc)
KEY = "SIM:P3"
TF = "1h"

#: The generating process. `PHI` near 1 makes the next step strongly predictable
#: from the last, which is the point: P3 asks whether the pipeline can learn a
#: structure that is definitely there, not whether markets have one.
PHI = 0.97
NOISE = 0.001
#: E[cumulative log return over 3 steps | last step s] = s · (φ + φ² + φ³)
TRUTH_FACTOR = sum(PHI ** k for k in range(1, 4))

SPEC = D.DatasetSpec(instrument_keys=(KEY,), timeframe=TF, lookback=17, horizon=3)
CONFIG = N.NeuralConfig(lookback=17, horizon=3, patch_len=4, d_model=16,
                        n_layers=2, epochs=80, batch_size=64,
                        learning_rate=1e-2)


def bars(prices) -> list[Candle]:
    return [Candle(instrument_key=KEY, timeframe=TF,
                   ts_open=START + timedelta(hours=i),
                   ts_close=START + timedelta(hours=i + 1),
                   open=p, high=p * 1.004, low=p * 0.996, close=p,
                   volume=1000.0 + i)
            for i, p in enumerate(prices)]


def ar1_series(n=1400, seed=5, phi=PHI, noise=NOISE):
    """AR(1) on log steps — a series whose conditional mean is known exactly."""
    rng = random.Random(seed)
    prices, step = [100.0], 0.0
    for _ in range(n - 1):
        step = phi * step + rng.gauss(0.0, noise)
        prices.append(prices[-1] * math.exp(step))
    return prices


def random_walk(n=1400, seed=9, sigma=0.003):
    """No structure at all. The negative control."""
    rng = random.Random(seed)
    prices = [100.0]
    for _ in range(n - 1):
        prices.append(prices[-1] * math.exp(rng.gauss(0.0, sigma)))
    return prices


@pytest.fixture(scope="module")
def fitted():
    """One fit, reused. Training is seconds, not milliseconds."""
    return T.train_neural(bars(ar1_series()), spec=SPEC, config=CONFIG,
                          checkpoint_id="p3-structured", seed=0,
                          clock=FixedClock(START + timedelta(days=90)))


@pytest.fixture(scope="module")
def on_noise():
    return T.train_neural(bars(random_walk()), spec=SPEC, config=CONFIG,
                          checkpoint_id="p3-walk", seed=0,
                          clock=FixedClock(START + timedelta(days=90)))


def median_predictions(result):
    """`(predicted terminal median, realised terminal, true conditional mean)`."""
    model = N.NeuralQuantileModel.from_parameters(result.checkpoint.parameters)
    labels = [quantile_label(q) for q in model.config.quantiles]
    median = labels[model.config.median_index]
    predicted, realised, truth = [], [], []
    for window in result.split.test:
        prediction = model.predict_from_bars(window.inputs)
        if isinstance(prediction, Declined):
            continue
        closes = [b.close for b in window.inputs]
        predicted.append(prediction.log_return_quantiles[median][-1])
        realised.append(window.target_log_returns()[-1])
        truth.append(math.log(closes[-1] / closes[-2]) * TRUTH_FACTOR)
    return predicted, realised, truth


# ===========================================================================
# P3's exit condition
# ===========================================================================

def test_the_fit_converges(fitted):
    report = fitted.train_report
    assert report["train_loss"][-1] < report["train_loss"][0], "loss did not fall"
    assert report["converged"] is True, (
        "a loss still falling at the last epoch has not converged, it ran out "
        "of epochs")
    assert report["parameters"] > 0


def test_the_model_recovers_the_known_conditional_mean(fitted):
    """The load-bearing assertion of P3.

    Correlated against the *true* conditional expectation, which this file's
    generating process makes available in closed form. A model can track
    realised prices by luck; it cannot track the true conditional mean by luck.
    """
    predicted, _, truth = median_predictions(fitted)
    assert len(predicted) > 100
    correlation = statistics.correlation(predicted, truth)
    assert correlation > 0.35, (
        f"predicted median correlates only {correlation:.3f} with the known "
        "conditional mean; the pipeline did not recover the structure")


def test_whether_the_model_beats_persistence_is_measured_not_asserted(fitted):
    """This test used to assert a win. It does not any more, and that is a
    finding rather than a loosening.

    The original assertion was `fmean(gains) > 0` — the model beats persistence
    on a series where structure genuinely exists. It passed on the torch build
    in the development container and **failed on GitHub's CPU-only build**, at
    a mean gain of -0.0037. Two things follow, and neither of them is "raise
    the tolerance":

    * a superiority claim that depends on which BLAS the tensor library was
      linked against is not a superiority claim, and
    * the project's own matched evaluation already says the opposite. Blocker
      **B9** in `native/quarantine.py` records that on identical data, costs,
      splits and metrics the native arm loses to persistence, to a linear fit
      and to a gradient-boosted tree. A unit test asserting the reverse on one
      favourable series was asserting something the evaluation had already
      contradicted.

    So the measurement stays and the claim goes. What is asserted here is that
    the comparison is *well formed* — the arrays line up, the numbers are
    finite, the bootstrap runs. Whether the sign is positive is reported, and
    `test_the_model_recovers_the_known_conditional_mean` above remains the
    load-bearing assertion about what the pipeline can do.
    """
    predicted, realised, _ = median_predictions(fitted)
    assert len(predicted) == len(realised) > 100
    model_error = [abs(p - a) for p, a in zip(predicted, realised)]
    # Persistence: the price does not move, so cumulative log return is zero.
    baseline_error = [abs(0.0 - a) for a in realised]
    gains = [b - m for b, m in zip(baseline_error, model_error)]
    assert all(math.isfinite(g) for g in gains)

    test = paired_bootstrap(gains, name="mae_reduction", seed=0)
    mean_gain = statistics.fmean(gains)
    assert math.isfinite(mean_gain)
    assert math.isfinite(test.p_value) and 0.0 <= test.p_value <= 1.0
    # Recorded so a reader of the CI log sees the number rather than inferring
    # it from a green tick.
    print(f"\nmean MAE gain against persistence: {mean_gain:+.6f} "
          f"(p={test.p_value:.4f}, significant={test.significant}) — "
          f"{'ahead' if mean_gain > 0 else 'behind'} on this build")


def test_the_model_does_not_beat_persistence_on_a_random_walk(on_noise):
    """The control. A suite that only demonstrates success cannot tell a
    working evaluation from a flattering one — and a model that 'beat' a
    persistence baseline on white noise would mean the harness is broken, not
    that the model is good."""
    predicted, realised, _ = median_predictions(on_noise)
    model_error = [abs(p - a) for p, a in zip(predicted, realised)]
    baseline_error = [abs(0.0 - a) for a in realised]
    gains = [b - m for b, m in zip(baseline_error, model_error)]
    improved = statistics.fmean(gains) > 0 and paired_bootstrap(
        gains, seed=0).significant
    assert not improved, (
        "the model reports a significant edge on white noise, which means the "
        "evaluation is measuring something other than skill")


def test_training_loss_falls_even_on_noise(on_noise):
    """Fitting the training set is not evidence of anything.

    Stated as its own test because 'the loss went down' is the number most
    often mistaken for a result, and here it goes down on a series with no
    structure whatsoever.
    """
    curve = on_noise.train_report["train_loss"]
    assert curve[-1] < curve[0]


# ===========================================================================
# determinism — gate G7 for a stochastic optimiser
# ===========================================================================

def test_the_same_seed_produces_identical_weights():
    a = T.train_neural(bars(ar1_series()), spec=SPEC, config=CONFIG,
                       checkpoint_id="det-a", seed=0)
    b = T.train_neural(bars(ar1_series()), spec=SPEC, config=CONFIG,
                       checkpoint_id="det-b", seed=0)
    assert a.checkpoint.parameters["trunk_weights"] == \
        b.checkpoint.parameters["trunk_weights"]
    assert a.checkpoint.parameters["encoder_weights"] == \
        b.checkpoint.parameters["encoder_weights"]


def test_a_different_seed_produces_different_weights():
    """Otherwise the seed is decorative and the determinism test above is
    passing for the wrong reason."""
    a = T.train_neural(bars(ar1_series()), spec=SPEC, config=CONFIG,
                       checkpoint_id="seed-a", seed=0)
    b = T.train_neural(bars(ar1_series()), spec=SPEC, config=CONFIG,
                       checkpoint_id="seed-b", seed=1)
    assert a.checkpoint.parameters["trunk_weights"] != \
        b.checkpoint.parameters["trunk_weights"]


# ===========================================================================
# the architecture's own guarantees
# ===========================================================================

def test_quantiles_cannot_cross(fitted):
    """Monotone by construction, not by penalty. A p95 below a p05 is not a
    wide interval, it is a nonsense one that flows into a stop-loss."""
    model = N.NeuralQuantileModel.from_parameters(fitted.checkpoint.parameters)
    labels = [quantile_label(q) for q in model.config.quantiles]
    checked = 0
    for window in fitted.split.test[:50]:
        prediction = model.predict_from_bars(window.inputs)
        if isinstance(prediction, Declined):
            continue
        checked += 1
        for step in range(model.config.horizon):
            ladder = [prediction.log_return_quantiles[l][step] for l in labels]
            assert ladder == sorted(ladder), f"quantiles crossed at step {step}"
    assert checked > 10


def test_the_trunk_is_causal_by_construction():
    """A causal convolution *cannot* read a future patch. Verified by changing
    only the last patch and checking earlier positions do not move — a masked
    attention implementation would need the same test and could fail it."""
    torch = TU.require_torch()
    TU.configure_determinism(0)
    config = TR.TrunkConfig(d_model=8, kernel_size=2, n_layers=2, horizon=2,
                            n_quantiles=3)
    trunk = TR.build_trunk(config)
    patches = torch.randn(1, 6, 8, generator=torch.Generator().manual_seed(1))

    blocks = trunk.blocks
    def hidden(x):
        h = x.transpose(1, 2)
        for block in blocks:
            h = block(h)
        return h

    before = hidden(patches)
    altered = patches.clone()
    altered[0, -1, :] += 10.0                    # change only the last patch
    after = hidden(altered)
    # Every position except the last must be untouched.
    assert torch.allclose(before[:, :, :-1], after[:, :, :-1], atol=1e-6), (
        "an earlier position changed when a later patch changed: the trunk is "
        "reading its own future")
    assert not torch.allclose(before[:, :, -1], after[:, :, -1])


def test_the_receptive_field_is_arithmetic_not_measured():
    config = TR.TrunkConfig(kernel_size=2, n_layers=3, horizon=1, n_quantiles=2)
    assert config.receptive_field == 1 + 2 * 1 * (2 ** 3 - 1)


def test_the_encoder_refuses_a_ragged_patch_grid():
    """Padding the *oldest* bars with zeros would teach the model that history
    began with a flat market."""
    with pytest.raises(ConfigurationError) as exc:
        E.EncoderConfig(lookback=10, patch_len=4)
    assert "ragged final patch" in str(exc.value)


def test_channels_are_scale_free():
    """A model trained on absolute prices learns the price level, which is the
    one thing guaranteed not to generalise."""
    cheap = bars([100.0 * (1.01 ** i) for i in range(20)])
    dear = bars([100_000.0 * (1.01 ** i) for i in range(20)])
    a = E.bars_to_channels(cheap)
    b = E.bars_to_channels(dear)
    assert a[0] == pytest.approx(b[0]), "log returns must not depend on level"


def test_normalisation_uses_the_window_only():
    """Causal because `data.Window` guarantees targets close after inputs — the
    §12.9 failure is normalising over a range that includes the horizon."""
    channels = E.bars_to_channels(bars(ar1_series(60)))
    normalised, stats = E.normalise_window(channels)
    assert len(stats) == len(E.CHANNELS)
    assert statistics.fmean(normalised[0]) == pytest.approx(0.0, abs=1e-9)


def test_a_constant_window_does_not_divide_by_zero():
    channels = E.bars_to_channels(bars([100.0] * 30))
    normalised, _ = E.normalise_window(channels)
    assert all(math.isfinite(v) for column in normalised for v in column)


# ===========================================================================
# refusals
# ===========================================================================

def test_an_unfitted_model_declines():
    model = N.NeuralQuantileModel(CONFIG)
    assert model.predict_from_bars(bars(ar1_series(17))) is DECLINE_NOT_FITTED


def test_a_short_window_declines(fitted):
    model = N.NeuralQuantileModel.from_parameters(fitted.checkpoint.parameters)
    assert model.predict_from_bars(bars(ar1_series(5))) is N.DECLINE_SHORT_WINDOW


def test_an_out_of_range_window_declines(fitted):
    """A window whose volatility is far outside anything seen in training is an
    input the model has no basis for."""
    from olympus.trading.native.quantile import DECLINE_OUT_OF_RANGE
    model = N.NeuralQuantileModel.from_parameters(fitted.checkpoint.parameters)
    wild = bars([100.0 * (1.5 ** (i % 3)) for i in range(CONFIG.lookback)])
    assert model.predict_from_bars(wild) is DECLINE_OUT_OF_RANGE


def test_the_feature_dict_entry_point_declines():
    """A patch encoder reads the shape of a window; a handful of summary
    features is not that input, and answering anyway would produce a number
    from something the model was never shown."""
    from olympus.trading.native.quantile import DECLINE_MISSING_FEATURE
    model = N.NeuralQuantileModel(CONFIG)
    assert model.predict({"rsi_14": 50.0}) is DECLINE_MISSING_FEATURE


def test_a_lookback_mismatch_between_dataset_and_encoder_is_refused():
    other = D.DatasetSpec(instrument_keys=(KEY,), timeframe=TF, lookback=33,
                          horizon=3)
    with pytest.raises(ConfigurationError) as exc:
        T.train_neural(bars(ar1_series(400)), spec=other, config=CONFIG,
                       checkpoint_id="x")
    assert "encoder would receive a window it was not built for" in str(exc.value)


def test_the_trainer_refuses_foreign_weights():
    with pytest.raises(CP.ForeignWeightsRefused):
        T.train_neural(bars(ar1_series(400)), spec=SPEC, config=CONFIG,
                       checkpoint_id="x",
                       continue_from="https://example.invalid/model.safetensors")


def test_a_single_quantile_is_refused():
    with pytest.raises(ConfigurationError) as exc:
        N.NeuralConfig(lookback=8, horizon=1, patch_len=1, quantiles=(0.5,))
    assert "no interval" in str(exc.value)


# ===========================================================================
# checkpoint and serving
# ===========================================================================

def test_the_checkpoint_records_the_torch_version(fitted):
    """The same code on a different tensor library is different code."""
    assert fitted.checkpoint.manifest.versions["torch"]
    assert fitted.checkpoint.model_kind == "olympus-neural-quantile"


def test_the_manifest_records_the_channel_set(fitted):
    """A patch encoder's feature set is its channels, not the named features
    the statistical estimator conditions on."""
    assert fitted.checkpoint.manifest.feature_names == E.CHANNELS


def test_weights_round_trip_through_the_checkpoint(fitted):
    model = N.NeuralQuantileModel.from_parameters(fitted.checkpoint.parameters)
    again = N.NeuralQuantileModel.from_parameters(model.to_parameters())
    window = fitted.split.test[0].inputs
    assert model.predict_from_bars(window).log_return_quantiles == \
        again.predict_from_bars(window).log_return_quantiles


def test_mismatched_weights_are_refused_rather_than_loaded(fitted):
    """A silent shape mismatch is a model producing plausible numbers from the
    wrong parameters."""
    parameters = dict(fitted.checkpoint.parameters)
    broken = {k: dict(v) for k, v in parameters["trunk_weights"].items()}
    name = sorted(broken)[0]
    broken[name] = {"shape": [99, 99], "values": [0.0] * (99 * 99)}
    parameters["trunk_weights"] = broken
    with pytest.raises(ConfigurationError) as exc:
        N.NeuralQuantileModel.from_parameters(parameters)
    assert "wrong shape" in str(exc.value)


def test_the_neural_forecaster_serves_through_the_standard_interface(fitted):
    """The point of the estimator registry: the same `NativeForecaster` serves
    a statistical checkpoint and a neural one."""
    clock = FixedClock(START + timedelta(days=90))
    forecaster = F.NativeForecaster(fitted.checkpoint, clock=clock)
    assert forecaster.consumes_bars is True
    assert forecaster.required_bars == CONFIG.lookback

    window = bars(ar1_series())[:400]
    produced = forecaster.forecast(window[-CONFIG.lookback:],
                                   as_of=window[-1].ts_close)
    if produced.abstained:
        assert produced.failure_code == F.CODE_MODEL_DECLINED
        return
    assert produced.horizon == CONFIG.horizon
    assert len(produced.quantiles) == len(CONFIG.quantiles)
    assert produced.model_identity["owner"] == "olympus"
    assert 0.0 <= produced.uncertainty <= 1.0


def test_the_neural_forecaster_registers_beside_the_baselines(fitted):
    from olympus.trading.forecast import ForecastService, PersistenceForecaster
    clock = FixedClock(START + timedelta(days=90))
    service = ForecastService(clock=clock)
    service.register("persistence", PersistenceForecaster(horizon=3, clock=clock))
    service.register("olympus-native", F.NativeForecaster(fitted.checkpoint,
                                                          clock=clock))
    window = bars(ar1_series())[:400]
    for name in service.names:
        produced = service.run(name, candles=window[-CONFIG.lookback:],
                               as_of=window[-1].ts_close,
                               instrument_key=KEY, timeframe=TF)
        assert produced.model_version


def test_held_out_evaluation_reports_coverage_and_abstentions(fitted):
    metrics = T.evaluate_neural_on_split(fitted.checkpoint, fitted.split)
    assert metrics["answered"] > 0
    assert metrics["abstention_rate"] is not None
    assert metrics["nominal_coverage"] == pytest.approx(0.9)
    assert metrics["realised_coverage"] is not None


# ===========================================================================
# the dependency boundary
# ===========================================================================

def test_torch_absence_raises_a_typed_error_not_an_import_error(monkeypatch):
    """`ImportError` reads as a broken installation; this is a feature that was
    not installed, which is a different conversation with the operator."""
    import builtins
    real = builtins.__import__

    def blocked(name, *args, **kwargs):
        if name == "torch" or name.startswith("torch."):
            raise ImportError("no torch")
        return real(name, *args, **kwargs)

    monkeypatch.setattr(builtins, "__import__", blocked)
    import importlib
    module = importlib.reload(TU)
    try:
        with pytest.raises(DependencyMissing) as exc:
            module.require_torch()
        assert exc.value.details["extra"] == "native"
        assert module.torch_available() is False
    finally:
        monkeypatch.undo()
        importlib.reload(TU)


def test_the_statistical_estimator_still_serves_without_torch():
    """The reason the native package does not require a tensor library: the
    trading core runs on a base install, and a native model that made torch
    mandatory would take that away from everyone who never asked for one."""
    from olympus.trading.native.quantile import ConditionalQuantileModel
    assert ConditionalQuantileModel.KIND in F._estimators()
