"""Portable replay fixtures (Wave 1 C2 — extends replaystore).

What these tests prove:

1. I-R1 — a fixture round-trip (record → export → import into a FRESH
   MEMORY_DIR → re-run under OLYMPUS_REPLAY) yields diff_decisions == []: the
   fixture carries everything exact-mode replay needs, portably.
2. I-R2 — export REFUSES a fixture containing anything that matches the
   secret-pattern screen (planted `sk-…` key), naming the offending file.
3. Reject-never-repair — one tampered byte, an unlisted file, or a missing
   referenced blob refuses the WHOLE fixture (typed errors, no partial state).
4. I-R3 — import never overwrites existing store entries unless force=True.
5. The committed CI fixture (tests/fixtures/replay/mini) imports cleanly and
   replays byte-identically — the fixture is generated ONCE (see the module
   docstring of the generator note below) and never regenerated by tests.

The record path reuses tests/test_decisionlog.py's _mini_pipeline +
_fake_client: the same faithful miniature of orchestrator._pipeline's decision
wiring, through the real backend.complete_json / llm.complete / replaystore.
"""

import json
from pathlib import Path

import pytest

import test_decisionlog as dl
from olympus import config, llm, replaystore, trace

MINI_FIXTURE = Path(__file__).parent / "fixtures" / "replay" / "mini"


# --- helpers ---------------------------------------------------------------

def _record_run(monkeypatch, memory_dir: Path, text: str = "do the thing"):
    """Record a _mini_pipeline run (route+plan+review) into `memory_dir`."""
    monkeypatch.setattr(config, "MEMORY_DIR", memory_dir)
    counter = [0]
    monkeypatch.setattr(
        llm, "client",
        lambda settings=None: dl._fake_client(counter, dl._responder))
    rec = trace.Trace("chat", "shared")
    rec.meta = {"input": text}
    dl._mini_pipeline(rec, text)
    rec.flush()
    assert counter[0] == 3
    return rec


def _forbid_network(monkeypatch):
    monkeypatch.setattr(llm, "client", lambda settings=None: (_ for _ in ()).throw(
        AssertionError("replay must not call the Anthropic API")))


# --- mode taxonomy helper ---------------------------------------------------

def test_replay_mode_names_exact_vs_live(monkeypatch):
    monkeypatch.delenv("OLYMPUS_REPLAY", raising=False)
    assert replaystore.replay_mode() == "live"
    monkeypatch.setenv("OLYMPUS_REPLAY", "some-run")
    assert replaystore.replay_mode() == "exact"


# --- I-R1: round-trip determinism -------------------------------------------

def test_fixture_roundtrip_replays_byte_identical(tmp_path, monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    fixture = replaystore.export_fixture(rec.id, tmp_path / "fx")
    assert (fixture / "manifest.json").exists()

    # Import into a FRESH store — nothing from the recording dir carries over.
    monkeypatch.setattr(config, "MEMORY_DIR", tmp_path / "B")
    run_id = replaystore.import_fixture(fixture)
    assert run_id == rec.id
    original = trace.load_run(run_id)
    assert original is not None      # traces/imported-<id>.jsonl is globbed

    # Re-run the SAME pipeline in exact replay mode against the imported store.
    monkeypatch.setenv("OLYMPUS_REPLAY", run_id)
    _forbid_network(monkeypatch)
    fresh = trace.Trace("replay", "shared")
    dl._mini_pipeline(fresh, original["meta"]["input"])
    assert trace.diff_decisions(original["decisions"], fresh.decisions) == []


def test_manifest_carries_flags_models_and_prompt_hashes(tmp_path, monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    fixture = replaystore.export_fixture(rec.id, tmp_path / "fx")
    manifest = json.loads((fixture / "manifest.json").read_text())
    assert manifest["v"] == "1.0" and manifest["run_id"] == rec.id
    # The flags fingerprint uses the EXACT env names replay_run reproduces.
    assert manifest["flags"]["OLYMPUS_ABC"] == "on"       # default-true meta
    assert manifest["flags"]["OLYMPUS_CONTRACTS"] == "0"
    assert {"provider": "anthropic", "model": "claude-test",
            "version": None} in manifest["models"]
    assert manifest["prompt_manifest"]["zeus"]            # prompts/*.md hashed
    assert manifest["scrub"] == {"screen": "v2", "matches": 0}
    listed = {f["path"] for f in manifest["files"]}
    assert "trace.json" in listed
    assert sum(p.startswith("responses/") for p in listed) == 3


# --- I-R2: secret screen refuses the export ---------------------------------

def test_export_refuses_planted_secret(tmp_path, monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    ref = rec.decisions[0]["model_response_ref"]
    blob = config.MEMORY_DIR / "responses" / f"{ref}.json"
    blob.write_text(blob.read_text().replace(
        "route", "sk-abcdef123456789"), encoding="utf-8")
    with pytest.raises(replaystore.FixtureSecretsError) as ei:
        replaystore.export_fixture(rec.id, tmp_path / "fx")
    assert f"responses/{ref}.json" in ei.value.files
    # no partial fixture was written
    assert not (tmp_path / "fx" / "manifest.json").exists()


# --- missing referenced blob refuses the export ------------------------------

def test_export_refuses_missing_referenced_blob(tmp_path, monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    ref = rec.decisions[1]["model_response_ref"]
    (config.MEMORY_DIR / "responses" / f"{ref}.json").unlink()
    with pytest.raises(replaystore.FixtureMissingBlobs) as ei:
        replaystore.export_fixture(rec.id, tmp_path / "fx")
    assert ref in ei.value.missing
    assert not (tmp_path / "fx" / "manifest.json").exists()


# --- tamper: reject-never-repair on import -----------------------------------

def test_import_refuses_tampered_byte(tmp_path, monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    fixture = replaystore.export_fixture(rec.id, tmp_path / "fx")
    victim = sorted((fixture / "responses").glob("*.json"))[0]
    data = bytearray(victim.read_bytes())
    data[len(data) // 2] ^= 0x01                    # flip one byte
    victim.write_bytes(bytes(data))

    monkeypatch.setattr(config, "MEMORY_DIR", tmp_path / "B")
    with pytest.raises(replaystore.FixtureHashMismatch):
        replaystore.import_fixture(fixture)
    # the whole fixture was refused: nothing materialized
    assert not (config.MEMORY_DIR / "traces").exists()
    assert not (config.MEMORY_DIR / "responses").exists()


def test_import_refuses_unlisted_extra_file(tmp_path, monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    fixture = replaystore.export_fixture(rec.id, tmp_path / "fx")
    (fixture / "responses" / ("e" * 64 + ".json")).write_text("{}")
    monkeypatch.setattr(config, "MEMORY_DIR", tmp_path / "B")
    with pytest.raises(replaystore.FixtureHashMismatch) as ei:
        replaystore.import_fixture(fixture)
    assert any("unlisted" in m for m in ei.value.mismatches)


# --- I-R3: force semantics ----------------------------------------------------

def test_import_refuses_existing_entries_without_force(tmp_path, monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    fixture = replaystore.export_fixture(rec.id, tmp_path / "fx")

    monkeypatch.setattr(config, "MEMORY_DIR", tmp_path / "B")
    assert replaystore.import_fixture(fixture) == rec.id
    with pytest.raises(replaystore.FixtureConflict):
        replaystore.import_fixture(fixture)             # second import refused
    # force=True is the explicit override
    assert replaystore.import_fixture(fixture, force=True) == rec.id
    # forced re-import didn't duplicate the trace record
    imported = (config.MEMORY_DIR / "traces" /
                f"imported-{rec.id}.jsonl").read_text()
    assert len(imported.strip().splitlines()) == 1


def test_import_refuses_when_recording_store_already_has_run(tmp_path,
                                                             monkeypatch):
    rec = _record_run(monkeypatch, tmp_path / "A")
    fixture = replaystore.export_fixture(rec.id, tmp_path / "fx")
    # Import back into the SAME store that recorded the run: both the response
    # blobs and the trace record already exist -> refuse without force.
    with pytest.raises(replaystore.FixtureConflict):
        replaystore.import_fixture(fixture)
    assert replaystore.import_fixture(fixture, force=True) == rec.id


# --- the committed CI fixture --------------------------------------------------

def test_committed_fixture_imports_verifies_and_replays(monkeypatch):
    """A4 evidence: the repo-committed fixture imports with every manifest hash
    passing, its trace record loads, and the recorded decision path replays
    byte-identically in a throwaway MEMORY_DIR (conftest isolates it)."""
    manifest = json.loads((MINI_FIXTURE / "manifest.json").read_text())
    run_id = replaystore.import_fixture(MINI_FIXTURE)   # verifies every sha
    assert run_id == manifest["run_id"]

    original = trace.load_run(run_id)
    assert original is not None
    assert len(original["decisions"]) == 3              # route + plan + review
    for d in original["decisions"]:
        assert replaystore.get(d["model_response_ref"]) is not None

    monkeypatch.setenv("OLYMPUS_REPLAY", run_id)
    _forbid_network(monkeypatch)
    fresh = trace.Trace("replay", "shared")
    dl._mini_pipeline(fresh, original["meta"]["input"])
    assert trace.diff_decisions(original["decisions"], fresh.decisions) == []


# --- CLI flags -------------------------------------------------------------------

def test_cli_export_fixture_flag(tmp_path, monkeypatch, capsys):
    from olympus import cli
    rec = _record_run(monkeypatch, tmp_path / "A")
    dest = tmp_path / "out-fixture"
    rc = cli.main(["replay", rec.id, "--export-fixture", str(dest)])
    out = capsys.readouterr().out
    assert (rc or 0) == 0
    assert (dest / "manifest.json").exists()
    assert str(dest) in out


def test_cli_export_fixture_requires_run_id(capsys):
    from olympus import cli
    rc = cli.main(["replay", "--export-fixture", "/nonexistent/x"])
    assert rc == 1


def test_cli_fixture_flag_imports_then_replays(monkeypatch, capsys):
    """--fixture imports into the live MEMORY_DIR then hands the imported
    run_id to the existing replay path. The full-orchestrator replay of the
    mini fixture would diverge (it was recorded through _mini_pipeline, not
    Olympus._pipeline), so the replay entry is monkeypatched: this test covers
    the import+lookup+dispatch wiring, the real replay determinism is proven
    library-level above."""
    from olympus import cli, orchestrator
    seen = {}

    def _fake_replay(run_id):
        seen["run_id"] = run_id
        original = trace.load_run(run_id)
        assert original is not None                 # imported before replay
        return original, trace.Trace("replay", "shared"), []

    monkeypatch.setattr(orchestrator, "replay_run", _fake_replay)
    rc = cli.main(["replay", "--fixture", str(MINI_FIXTURE)])
    out = capsys.readouterr().out
    manifest = json.loads((MINI_FIXTURE / "manifest.json").read_text())
    assert (rc or 0) == 0
    assert seen["run_id"] == manifest["run_id"]
    assert "Imported fixture run" in out and "byte-identically" in out


def test_cli_fixture_flag_refuses_bad_fixture(tmp_path, capsys):
    from olympus import cli
    (tmp_path / "notafixture").mkdir()
    rc = cli.main(["replay", "--fixture", str(tmp_path / "notafixture")])
    assert rc == 1
    assert "[error]" in capsys.readouterr().out


def test_cli_replay_without_run_id_or_fixture_errors(capsys):
    from olympus import cli
    rc = cli.main(["replay"])
    assert rc == 1
    assert "usage" in capsys.readouterr().out
