#!/usr/bin/env python3
"""Reproduce the Phase-2 run: train, serve, evaluate, and emit a model card.

Prints the reproducibility report, the stratified evaluation and the model card,
then writes the card to `docs/generated/` if `--write` is given.

**Every series here is synthetic and generated by this file.** The numbers say
what the pipeline does; they say nothing about markets, because no market-data
provider is reachable from this environment (blocker B1,
`docs/OLYMPUS_NATIVE_MODEL_STATUS.md` §4).

    python scripts/native_train_and_evaluate.py            # needs the `native` extra
    python scripts/native_train_and_evaluate.py --write

The evaluation includes an external-benchmark arm that is *unavailable*: no
third-party checkpoint is reachable (blocker B2) and its weight licence is
unverified (blocker B4). It is reported as missing rather than dropped, because
an evaluation that quietly loses its hardest opponent reads as complete.
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

from olympus.trading.clock import FixedClock
from olympus.trading.contracts import Candle
from olympus.trading.native import abstain as A
from olympus.trading.native import baselines as B
from olympus.trading.native import dataset as D
from olympus.trading.native import evaluation as E
from olympus.trading.native import model as M
from olympus.trading.native import modelcard as MC
from olympus.trading.native import originality as O
from olympus.trading.native import pipeline as P
from olympus.trading.native import serve as SV
from olympus.trading.native import torchutil as TU
from olympus.trading.native.data import make_windows

START = datetime(2027, 6, 1, tzinfo=timezone.utc)
KEY = "SIM:1"
LOOKBACK, HORIZON = 33, 3


def ar1(n: int = 1200, seed: int = 5, phi: float = 0.97,
        noise: float = 0.001) -> list[float]:
    rng = random.Random(seed)
    prices, step = [100.0], 0.0
    for _ in range(n - 1):
        step = phi * step + rng.gauss(0.0, noise)
        prices.append(prices[-1] * math.exp(step))
    return prices


def bars(prices) -> list[Candle]:
    return [Candle(instrument_key=KEY, timeframe="1h",
                   ts_open=START + timedelta(hours=i),
                   ts_close=START + timedelta(hours=i + 1),
                   open=p, high=p * 1.004, low=p * 0.996, close=p,
                   volume=1000.0 + i * (1 + 0.3 * math.sin(i / 40)))
            for i, p in enumerate(prices)]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--write", action="store_true",
                        help="write the model card to docs/generated/")
    parser.add_argument("--max-dispersion", type=float, default=3.0,
                        help="abstention threshold; raise it to see the "
                             "model's forecasts scored rather than declined")
    args = parser.parse_args()

    if not TU.torch_available():
        print("torch is absent: install the `native` extra to run this.")
        return 2

    print("=" * 96)
    print("PHASE 2 — SYNTHETIC DATA ONLY. Nothing here is evidence about markets.")
    print("=" * 96)

    windows = make_windows(bars(ar1()), lookback=LOOKBACK, horizon=HORIZON)
    split = D.three_way_split(windows, train_fraction=0.6,
                              validation_fraction=0.2)
    print(f"\ntrain/validation/test = {split.sizes}")

    config = M.ModelConfig(lookback=LOOKBACK, horizon=HORIZON, d_model=16,
                           expert_hidden=16)
    trainer = P.Trainer(config,
                        P.TrainingConfig(seed=args.seed, epochs=args.epochs,
                                         patience=12),
                        clock=FixedClock(START + timedelta(days=120)))
    record = trainer.fit(split.train, validation=split.validation,
                         dataset_hash="synthetic-ar1-" + "0" * 48)

    context = SV.build_serving_context(trainer.model, split.train, config)
    checkpoint = trainer.to_checkpoint(
        record, checkpoint_id="phase2", train_start=START,
        train_end=START + timedelta(days=40), feature_names=("log_return",))
    record = P.finalise(record, checkpoint, trainer.sign(checkpoint))

    print("\n### Reproducibility report\n")
    print(record.report())
    print(f"\n  per-task loss (final epoch): "
          f"{ {k: round(v, 6) for k, v in record.epochs[-1].per_task.items()} }")
    print(f"  dead heads: {record.dead_heads() or 'none'}")

    predictor = SV.MultiTaskPredictor(
        checkpoint, context=context, market="simulated",
        thresholds=A.AbstentionThresholds(
            max_dispersion_ratio=args.max_dispersion))
    forecasts = [predictor.forecast(w.inputs, as_of=w.inputs[-1].ts_close)
                 for w in split.test]
    observations = E.observations_from_forecasts(forecasts, split.test)

    baseline = B.build_baseline("persistence", horizon=HORIZON)
    baseline.fit(split.train)
    arm = []
    for window in split.test:
        prediction = baseline.predict_from_bars(window.inputs)
        arm.append(E.Observation(
            instrument_key=KEY, timeframe="1h", horizon=HORIZON,
            as_of=window.as_of,
            predicted=prediction.log_return_quantiles[
                prediction.median_label][-1],
            actual=window.target_log_returns()[-1],
            quantiles={k: v[-1]
                       for k, v in prediction.log_return_quantiles.items()}))

    from olympus.trading import kronos_adapter
    report = E.evaluate(
        observations, model_name="olympus-multitask",
        arms=[E.ComparisonArm(name="persistence", kind="persistence",
                              observations=arm),
              kronos_adapter.native_benchmark_arm()])

    print("\n### Stratified evaluation\n")
    print(report.table())
    print(f"\n  inference: {json.dumps(predictor.stats().to_dict())}")

    print("\n### Originality audit\n")
    audit = O.audit_report()
    print(f"  clean: {audit['clean']}  checks: {len(audit['checks_run'])}  "
          f"findings: {audit['n_findings']}")
    for check, findings in audit["by_check"].items():
        for finding in findings:
            print(f"    {check}: {finding['location']} {finding['detail']}")

    card = MC.build_card(
        name="olympus-multitask", version="1",
        created_at=START + timedelta(days=120), model_config=config,
        run_record=record, checkpoint=checkpoint, evaluation_report=report,
        abstention_policy=predictor.policy,
        performance=[
            MC.PerformanceClaim(
                metric="quantile_loss", value=report.overall.get("quantile_loss"),
                evidence=MC.EvidenceClass.SYNTHETIC_DATA,
                dataset="AR(1) phi=0.97, generated by this script",
                n=int(report.overall.get("n_scored", 0)),
                note=f"verdict against persistence: {report.verdict}"),
            MC.PerformanceClaim(
                metric="calibration_error_points",
                value=report.overall.get("calibration_error"),
                evidence=MC.EvidenceClass.SYNTHETIC_DATA,
                dataset="AR(1) phi=0.97, generated by this script",
                n=int(report.overall.get("n_scored", 0)),
                note="signed; positive means over-cautious"),
        ])

    print("\n### Model card (first 40 lines)\n")
    print("\n".join(card.to_markdown().splitlines()[:40]))

    if args.write:
        target = Path("docs/generated")
        target.mkdir(parents=True, exist_ok=True)
        MC.write_card(card, target / "olympus_multitask_model_card.md")
        print(f"\nwrote {target / 'olympus_multitask_model_card.md'}")

    if report.verdict == "better":
        print("\nNOTE: the model beat its baseline on synthetic data. That is a "
              "statement about this generating process and nothing else.")
    return 0


if __name__ == "__main__":                               # pragma: no cover
    sys.exit(main())
