#!/usr/bin/env python3
"""Phase 5 Step 15 — re-run the four deferred Wave-3 evidence gates.

THE FLOORS ARE NOT TOUCHED. This script reads `WAVE3_EVIDENCE_REVIEW.md`'s
thresholds as constants and re-measures against them; it has no mechanism for
lowering one. Phase-5 rule 6 forbids it, and a script that *could* do it would
be a temptation on a bad day.

Run:  python scripts/wave3_gate_rerun.py [--json]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# Verbatim from WAVE3_EVIDENCE_REVIEW.md §1. Constants, not parameters.
FLOORS = {
    "speculation": "a qualified draft AND verify model per cell, plus a "
                   "per-cell A/B showing acceptance pays for the second call",
    "prefetch": "recall@2 >= 0.6 with Wilson-CI half-width <= 0.1 on n >= 200",
    "local_tier": "modelgrade cards qualifying the local member per cell "
                  "(n >= MIN_N, Wilson >= floor, fresh)",
    "mirror": "a measured provider-unavailability rate worth mitigating, plus "
              "deterministic selection",
}


def measure() -> dict:
    from olympus import config, coupling, modelgrade, routesub, shadow

    grade = modelgrade.cards()
    # NOTE: `cards()` returns the whole document {version, cards, conflicts,
    # counts}. `len()` on it is 4 — the number of KEYS — which is why the
    # Wave-3 review's published reproduction command now prints a misleading
    # number. The card count is counts["cards"]. Recorded as finding W3R-1.
    card_count = grade["counts"]["cards"]
    evidence_rows = grade["counts"]["evidence_rows"]

    pred = coupling.predictability_report(days=30)
    sub = routesub.agreement_stats(days=30)
    intents = shadow.read_intents()

    stores = {}
    for name in ("traces", "modelgrade", "routesub", "ctxheat", "streamguard",
                 "watchdog", "usage", "shadow"):
        d = config.MEMORY_DIR / name
        stores[name] = len(list(d.rglob("*"))) if d.exists() else 0

    return {
        "modelgrade_cards": card_count,
        "modelgrade_evidence_rows": evidence_rows,
        "modelgrade_enabled": modelgrade.enabled(),
        "coupling_n_runs": pred["n_runs"],
        "coupling_status": pred["status"],
        "coupling_floors_pass": pred["floors"]["pass"],
        "coupling_qualifying": pred["floors"].get("qualifying", []),
        "routesub_decisions": sub["decisions"],
        "routesub_mode": sub["mode"],
        "shadow_intents": len(intents),
        "shadow_provenance_mix": sorted(
            {i.get("provenance", "?") for i in intents}),
        "evidence_stores": stores,
    }


def gates(m: dict) -> list[dict]:
    """Each gate's verdict, with the exact evidence behind it.

    `provenance` is the load-bearing column. Under Phase-5 rule 7, evidence
    generated by Olympus's own test and benchmark runs is SYNTHETIC and cannot
    satisfy a floor that exists to characterise real traffic — so a gate can
    fail on provenance even when a count looks non-zero."""
    return [
        {
            "id": 1,
            "candidate": "Lossless council speculation",
            "floor": FLOORS["speculation"],
            "measured": (f"modelgrade cards={m['modelgrade_cards']}, "
                         f"evidence rows={m['modelgrade_evidence_rows']}, "
                         f"flag enabled={m['modelgrade_enabled']}"),
            "n": m["modelgrade_cards"],
            "provenance": "none — no evidence rows exist",
            "verdict": "NO-GO",
            "why": ("No model is qualified as a draft or as a verifier for any "
                    "cell, so there is nothing to speculate WITH and no "
                    "acceptance rate to price the second call against."),
        },
        {
            "id": 2,
            "candidate": "Coupling-driven predictive prefetch",
            "floor": FLOORS["prefetch"],
            "measured": (f"n_runs={m['coupling_n_runs']}, "
                         f"status={m['coupling_status']}, "
                         f"floors.pass={m['coupling_floors_pass']}, "
                         f"qualifying={m['coupling_qualifying']}"),
            "n": m["coupling_n_runs"],
            "provenance": ("synthetic — the runs present were generated by "
                           "this repository's own test and harness executions, "
                           "not by traffic"),
            "verdict": "NO-GO",
            "why": (f"n={m['coupling_n_runs']} against a floor of n>=200, and "
                    f"the runs that do exist are synthetic. Rule 7: synthetic "
                    f"evidence may validate infrastructure but cannot satisfy "
                    f"a floor whose purpose is to characterise real traffic."),
        },
        {
            "id": 3,
            "candidate": "Local inference tier",
            "floor": FLOORS["local_tier"],
            "measured": (f"qualification cards={m['modelgrade_cards']}; no "
                         f"local runtime is installed in this environment"),
            "n": m["modelgrade_cards"],
            "provenance": "none — no campaign has been executed",
            "verdict": "NO-GO",
            "why": ("Qualifying a local member needs a local runtime to "
                    "qualify and a campaign to qualify it with. Neither "
                    "exists here."),
        },
        {
            "id": 4,
            "candidate": "Provider mirror routing",
            "floor": FLOORS["mirror"],
            "measured": (f"routesub decisions={m['routesub_decisions']}, "
                         f"mode={m['routesub_mode']}"),
            "n": m["routesub_decisions"],
            "provenance": "none — no decisions recorded",
            "verdict": "NO-GO",
            "why": ("Mirroring mitigates provider unavailability. No "
                    "unavailability rate has been measured, so the size of "
                    "the problem — and therefore whether the mitigation is "
                    "worth its cost — is unknown."),
        },
    ]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    m = measure()
    g = gates(m)
    payload = {"floors_modified": False, "measurements": m, "gates": g,
               "verdicts": {row["candidate"]: row["verdict"] for row in g}}

    if args.json:
        print(json.dumps(payload, indent=1, default=str))
        return 0

    print("=" * 88)
    print("PHASE 5 STEP 15 — WAVE-3 EVIDENCE GATES, RE-RUN")
    print("=" * 88)
    print("Floors are taken verbatim from WAVE3_EVIDENCE_REVIEW.md and are NOT")
    print("modified by this script (Phase-5 rule 6).")
    print("-" * 88)
    for row in g:
        print(f"\n[{row['id']}] {row['candidate']}")
        print(f"    FLOOR      : {row['floor']}")
        print(f"    MEASURED   : {row['measured']}")
        print(f"    SAMPLE n   : {row['n']}")
        print(f"    PROVENANCE : {row['provenance']}")
        print(f"    VERDICT    : {row['verdict']}")
        print(f"    WHY        : {row['why']}")
    print("\n" + "-" * 88)
    counts: dict[str, int] = {}
    for row in g:
        counts[row["verdict"]] = counts.get(row["verdict"], 0) + 1
    print("  ".join(f"{v}: {n}" for v, n in sorted(counts.items())))
    print("\nEvidence stores on disk:")
    for name, n in sorted(m["evidence_stores"].items()):
        print(f"  {name:<12} {n if n else 'absent'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
